### ISSUE TITLE
Add vcpkg support into ppp.vcxproj

### ISSUE THREAD

**Issue by wu2305** [liulilittle/openppp2#5]
Please add the following into the ppp.vcxproj
```xml
<PropertyGroup Label="Vcpkg">
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestInstall>true</VcpkgManifestInstall>
    <VcpkgConfiguration>$(Configuration)</VcpkgConfiguration>
    <VcpkgEnabled>true</VcpkgEnabled>
</PropertyGroup>
```
This would greatly help the automatic MSBuild actions to compile the ppp executable file

**Comment by wu2305** [comment]
Besides, @rebecca554owen and me has write the github actions to automatically generate release files. Would you mind to merge these workflow/*.yml to the main branch?

**Comment by liulilittle** [comment]
OK.
